//! Second-order servo effector.
//!
//! This is the WP-09.2 finite-bandwidth actuator substrate. It preserves the
//! scalar [`ControlEffector`] contract while adding a deterministic
//! second-order bandwidth model with command-side rate limiting,
//! acceleration limiting, backlash, position saturation, pure delay, and the
//! canonical fault modes, including deterministic oscillatory command
//! injection.

use std::collections::VecDeque;

use openbmp_core::{Duration, EffectorId};

use super::{ControlEffector, EffectorError, EffectorFault, EffectorLimits, EffectorState};

const DESCRIBING_FUNCTION_SAMPLES_PER_CYCLE: usize = 4096;
const DESCRIBING_FUNCTION_WARMUP_CYCLES: usize = 8;

/// Finite-bandwidth second-order servo parameters.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SecondOrderServoParams {
    /// Natural frequency `omega_n`, rad/s. Must be strictly positive.
    pub natural_frequency_rad_s: f64,
    /// Damping ratio `zeta`. Must be finite and non-negative.
    pub damping_ratio: f64,
    /// Maximum command acceleration magnitude, units/s^2.
    pub max_accel_per_s2: f64,
    /// Half-width of the backlash dead zone, in effector units.
    pub backlash_half_width: f64,
}

impl SecondOrderServoParams {
    fn require_valid(self, limits: EffectorLimits) -> Result<(), EffectorError> {
        if !self.natural_frequency_rad_s.is_finite() || self.natural_frequency_rad_s <= 0.0 {
            return Err(EffectorError::InvalidLimits {
                reason: "natural_frequency_rad_s must be finite and strictly positive",
            });
        }
        if !self.damping_ratio.is_finite() || self.damping_ratio < 0.0 {
            return Err(EffectorError::InvalidLimits {
                reason: "damping_ratio must be finite and non-negative",
            });
        }
        if !self.max_accel_per_s2.is_finite() || self.max_accel_per_s2 <= 0.0 {
            return Err(EffectorError::InvalidLimits {
                reason: "max_accel_per_s2 must be finite and strictly positive",
            });
        }
        if !self.backlash_half_width.is_finite() || self.backlash_half_width < 0.0 {
            return Err(EffectorError::InvalidLimits {
                reason: "backlash_half_width must be finite and non-negative",
            });
        }
        if self.backlash_half_width > 0.5 * (limits.max - limits.min) {
            return Err(EffectorError::InvalidLimits {
                reason: "backlash_half_width must be at most half the authority range",
            });
        }
        Ok(())
    }
}

/// First-harmonic describing-function evidence for the command-side rate-limit
/// plus backlash nonlinearity used by [`SecondOrderServo`].
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct RateLimitBacklashDescribingFunction {
    /// Sinusoidal input amplitude.
    pub input_amplitude: f64,
    /// Sinusoidal input frequency, Hz.
    pub frequency_hz: f64,
    /// Fundamental output amplitude after rate limiting and backlash.
    pub output_amplitude: f64,
    /// `output_amplitude / input_amplitude`.
    pub gain: f64,
    /// Positive phase lag of the output fundamental relative to input, rad.
    pub phase_lag_rad: f64,
    /// Fraction of the final cycle where the rate limiter was active.
    pub rate_limited_fraction: f64,
    /// Fraction of the final cycle where backlash held output constant.
    pub backlash_hold_fraction: f64,
}

/// Compute the deterministic describing-function estimate for the
/// [`SecondOrderServo`] command-side rate limiter followed by the backlash play
/// operator.
///
/// The estimate is generated by fixed-resolution quadrature over one final
/// sinusoidal cycle after a deterministic warm-up. This avoids relying on a
/// vendor actuator map while still producing a stable first-harmonic reference
/// for WP-09.2 rate-limit/backlash evidence.
///
/// # Errors
///
/// Returns [`EffectorError::InvalidLimits`] when any scalar is non-finite, the
/// amplitude/frequency/max-rate is not positive, or the backlash half-width is
/// negative.
pub fn rate_limit_backlash_describing_function(
    input_amplitude: f64,
    frequency_hz: f64,
    max_rate_per_s: f64,
    backlash_half_width: f64,
) -> Result<RateLimitBacklashDescribingFunction, EffectorError> {
    rate_limit_backlash_describing_function_with_resolution(
        input_amplitude,
        frequency_hz,
        max_rate_per_s,
        backlash_half_width,
        DESCRIBING_FUNCTION_SAMPLES_PER_CYCLE,
        DESCRIBING_FUNCTION_WARMUP_CYCLES,
    )
}

/// Second-order servo with rate, acceleration, backlash, saturation, and delay.
#[derive(Clone, Debug)]
pub struct SecondOrderServo {
    id: EffectorId,
    limits: EffectorLimits,
    params: SecondOrderServoParams,
    dt: Duration,
    latency_buffer: VecDeque<f64>,
    demand_position: f64,
    demand_rate: f64,
    actual: f64,
    actual_rate: f64,
    last_state: EffectorState,
    fault: Option<EffectorFault>,
    fault_elapsed_s: f64,
}

impl SecondOrderServo {
    /// Construct a second-order servo.
    ///
    /// # Errors
    ///
    /// Returns [`EffectorError`] when limits, parameters, `dt`, or the initial
    /// position are invalid.
    pub fn new(
        id: EffectorId,
        limits: EffectorLimits,
        params: SecondOrderServoParams,
        dt: Duration,
        initial_position: f64,
    ) -> Result<Self, EffectorError> {
        let dt_s = dt.as_seconds();
        if !dt_s.is_finite() || dt_s <= 0.0 {
            return Err(EffectorError::InvalidLimits {
                reason: "dt must be finite and strictly positive",
            });
        }
        limits.require_valid(dt)?;
        params.require_valid(limits)?;
        if !initial_position.is_finite() {
            return Err(EffectorError::NonFiniteCommand {
                value: initial_position,
            });
        }
        if initial_position < limits.min || initial_position > limits.max {
            return Err(EffectorError::InvalidLimits {
                reason: "initial_position must be within [min, max]",
            });
        }
        let latency_buffer = VecDeque::from(vec![
            initial_position;
            latency_buffer_depth(limits.latency, dt,)?
        ]);
        let last_state = EffectorState::at_rest(initial_position);
        Ok(Self {
            id,
            limits,
            params,
            dt,
            latency_buffer,
            demand_position: initial_position,
            demand_rate: 0.0,
            actual: initial_position,
            actual_rate: 0.0,
            last_state,
            fault: None,
            fault_elapsed_s: 0.0,
        })
    }

    /// Current output rate of the bandwidth filter, units/s.
    #[must_use]
    pub const fn actual_rate(&self) -> f64 {
        self.actual_rate
    }

    fn validate_fault(&self, fault: EffectorFault) -> Result<(), EffectorError> {
        match fault {
            EffectorFault::Jam { at } => {
                if !at.is_finite() {
                    return Err(EffectorError::InvalidFault {
                        reason: "Jam.at must be finite",
                    });
                }
                if at < self.limits.min || at > self.limits.max {
                    return Err(EffectorError::InvalidFault {
                        reason: "Jam.at must lie within [min, max]",
                    });
                }
            }
            EffectorFault::Runaway { rate_per_s } => {
                if !rate_per_s.is_finite() {
                    return Err(EffectorError::InvalidFault {
                        reason: "Runaway.rate_per_s must be finite",
                    });
                }
            }
            EffectorFault::ReducedRate { factor } => {
                if !factor.is_finite() {
                    return Err(EffectorError::InvalidFault {
                        reason: "ReducedRate.factor must be finite",
                    });
                }
                if !(0.0..=1.0).contains(&factor) {
                    return Err(EffectorError::InvalidFault {
                        reason: "ReducedRate.factor must lie in [0, 1]",
                    });
                }
            }
            EffectorFault::Hardover { to } => {
                if !to.is_finite() {
                    return Err(EffectorError::InvalidFault {
                        reason: "Hardover.to must be finite",
                    });
                }
                if to < self.limits.min || to > self.limits.max {
                    return Err(EffectorError::InvalidFault {
                        reason: "Hardover.to must lie within [min, max]",
                    });
                }
            }
            EffectorFault::Oscillatory {
                amplitude,
                frequency_hz,
                phase_rad,
            } => {
                if !amplitude.is_finite() || amplitude < 0.0 {
                    return Err(EffectorError::InvalidFault {
                        reason: "Oscillatory.amplitude must be finite and non-negative",
                    });
                }
                if !frequency_hz.is_finite() || frequency_hz <= 0.0 {
                    return Err(EffectorError::InvalidFault {
                        reason: "Oscillatory.frequency_hz must be finite and strictly positive",
                    });
                }
                if !phase_rad.is_finite() {
                    return Err(EffectorError::InvalidFault {
                        reason: "Oscillatory.phase_rad must be finite",
                    });
                }
            }
        }
        Ok(())
    }

    fn delayed_command(&mut self, cmd: f64) -> f64 {
        if self.latency_buffer.is_empty() {
            cmd
        } else {
            self.latency_buffer.push_back(cmd);
            self.latency_buffer.pop_front().unwrap_or(cmd)
        }
    }

    fn command_target(&mut self, target: f64, dt_s: f64) -> (f64, bool) {
        let max_rate_unmodified = self.limits.max_rate_per_s;
        let max_rate = match self.fault {
            Some(EffectorFault::ReducedRate { factor }) => {
                max_rate_unmodified * factor.clamp(0.0, 1.0)
            }
            _ => max_rate_unmodified,
        };
        let requested_rate = ((target - self.demand_position) / dt_s).clamp(-max_rate, max_rate);
        let rate_limited = ((target - self.demand_position) / dt_s - requested_rate).abs() > 0.0;

        let max_rate_delta = self.params.max_accel_per_s2 * dt_s;
        let requested_delta = requested_rate - self.demand_rate;
        let clamped_delta = requested_delta.clamp(-max_rate_delta, max_rate_delta);
        let accel_limited = (requested_delta - clamped_delta).abs() > 0.0;
        self.demand_rate += clamped_delta;
        self.demand_position += self.demand_rate * dt_s;

        if self.demand_position < self.limits.min {
            self.demand_position = self.limits.min;
            if self.demand_rate < 0.0 {
                self.demand_rate = 0.0;
            }
        } else if self.demand_position > self.limits.max {
            self.demand_position = self.limits.max;
            if self.demand_rate > 0.0 {
                self.demand_rate = 0.0;
            }
        }

        (self.demand_position, rate_limited || accel_limited)
    }

    fn backlash_target(&self, demand: f64) -> f64 {
        let half_width = self.params.backlash_half_width;
        if half_width == 0.0 {
            return demand;
        }
        let delta = demand - self.actual;
        if delta.abs() <= half_width {
            self.actual
        } else {
            demand - half_width.copysign(delta)
        }
    }

    fn apply_bandwidth(&mut self, target: f64, dt_s: f64) -> bool {
        let (new_actual, new_rate) = second_order_exact_step(
            self.actual,
            self.actual_rate,
            target,
            self.params.natural_frequency_rad_s,
            self.params.damping_ratio,
            dt_s,
        );
        let mut saturated = false;
        self.actual = new_actual;
        self.actual_rate = new_rate;
        if self.actual < self.limits.min {
            self.actual = self.limits.min;
            if self.actual_rate < 0.0 {
                self.actual_rate = 0.0;
            }
            saturated = true;
        } else if self.actual > self.limits.max {
            self.actual = self.limits.max;
            if self.actual_rate > 0.0 {
                self.actual_rate = 0.0;
            }
            saturated = true;
        }
        saturated
    }
}

impl ControlEffector for SecondOrderServo {
    fn id(&self) -> EffectorId {
        self.id
    }

    fn step(&mut self, cmd: f64, dt: Duration) -> Result<EffectorState, EffectorError> {
        let configured_s = self.dt.as_seconds();
        let got_s = dt.as_seconds();
        if (configured_s - got_s).abs() > 1.0e-12 {
            return Err(EffectorError::DtMismatch {
                configured_s,
                got_s,
            });
        }
        if !cmd.is_finite() {
            return Err(EffectorError::NonFiniteCommand { value: cmd });
        }
        let effective_cmd = if let Some(fault) = self.fault {
            if let Some(offset) = fault.oscillatory_offset(self.fault_elapsed_s) {
                let value = cmd + offset;
                if !value.is_finite() {
                    return Err(EffectorError::NonFiniteCommand { value });
                }
                self.fault_elapsed_s += got_s;
                value
            } else {
                cmd
            }
        } else {
            cmd
        };

        if let Some(fault) = self.fault {
            match fault {
                EffectorFault::Jam { at } => {
                    self.actual = at;
                    self.actual_rate = 0.0;
                    self.demand_position = at;
                    self.demand_rate = 0.0;
                    let saturated =
                        self.actual <= self.limits.min || self.actual >= self.limits.max;
                    let state = EffectorState {
                        commanded: cmd,
                        actual: self.actual,
                        saturated,
                        rate_limited: true,
                        fault: Some(fault),
                    };
                    self.last_state = state;
                    return Ok(state);
                }
                EffectorFault::Hardover { to } => {
                    let raw_delta = to - self.actual;
                    let step_limit = self.limits.max_rate_per_s * got_s;
                    let delta = raw_delta.clamp(-step_limit, step_limit);
                    self.actual = (self.actual + delta).clamp(self.limits.min, self.limits.max);
                    self.actual_rate = delta / got_s;
                    self.demand_position = self.actual;
                    self.demand_rate = self.actual_rate;
                    let saturated =
                        self.actual <= self.limits.min || self.actual >= self.limits.max;
                    let state = EffectorState {
                        commanded: cmd,
                        actual: self.actual,
                        saturated,
                        rate_limited: true,
                        fault: Some(fault),
                    };
                    self.last_state = state;
                    if raw_delta.abs() <= step_limit + 1.0e-12 {
                        self.fault = Some(EffectorFault::Jam { at: self.actual });
                    }
                    return Ok(state);
                }
                EffectorFault::Runaway { rate_per_s } => {
                    let proposed = self.actual + rate_per_s * got_s;
                    let saturated = proposed < self.limits.min || proposed > self.limits.max;
                    self.actual = proposed.clamp(self.limits.min, self.limits.max);
                    self.actual_rate = rate_per_s;
                    self.demand_position = self.actual;
                    self.demand_rate = rate_per_s;
                    let state = EffectorState {
                        commanded: cmd,
                        actual: self.actual,
                        saturated,
                        rate_limited: false,
                        fault: Some(fault),
                    };
                    self.last_state = state;
                    return Ok(state);
                }
                EffectorFault::ReducedRate { .. } => {}
                EffectorFault::Oscillatory { .. } => {}
            }
        }

        let delayed_cmd = self.delayed_command(effective_cmd);
        let target_pre_clamp = if (delayed_cmd - self.actual).abs() < self.limits.deadband {
            self.actual
        } else {
            delayed_cmd
        };
        let target = target_pre_clamp.clamp(self.limits.min, self.limits.max);
        let saturated_command =
            target_pre_clamp < self.limits.min || target_pre_clamp > self.limits.max;
        let (demand, limited) = self.command_target(target, got_s);
        let backlash_target = self.backlash_target(demand);
        let saturated_output = self.apply_bandwidth(backlash_target, got_s);

        let state = EffectorState {
            commanded: effective_cmd,
            actual: self.actual,
            saturated: saturated_command || saturated_output,
            rate_limited: limited,
            fault: self.fault,
        };
        self.last_state = state;
        Ok(state)
    }

    fn limits(&self) -> EffectorLimits {
        self.limits
    }

    fn inject_fault(&mut self, fault: EffectorFault) -> Result<(), EffectorError> {
        self.validate_fault(fault)?;
        self.fault = Some(fault);
        Ok(())
    }

    fn current_state(&self) -> EffectorState {
        self.last_state
    }
}

fn latency_buffer_depth(latency: Duration, dt: Duration) -> Result<usize, EffectorError> {
    let latency_s = latency.as_seconds();
    let dt_s = dt.as_seconds();
    if latency_s == 0.0 {
        return Ok(0);
    }
    let ratio = latency_s / dt_s;
    let rounded = ratio.round();
    if (ratio - rounded).abs() > 1.0e-9 * ratio {
        return Err(EffectorError::InvalidLimits {
            reason: "latency must be an integer multiple of dt",
        });
    }
    #[allow(clippy::cast_sign_loss, clippy::cast_possible_truncation)]
    Ok(rounded as usize)
}

fn second_order_exact_step(
    actual: f64,
    rate: f64,
    target: f64,
    omega_n: f64,
    damping: f64,
    dt_s: f64,
) -> (f64, f64) {
    let error0 = actual - target;
    if damping < 1.0 - 1.0e-12 {
        let omega_d = omega_n * (1.0 - damping * damping).sqrt();
        let decay = (-damping * omega_n * dt_s).exp();
        let (sin_wd, cos_wd) = (omega_d * dt_s).sin_cos();
        let a = error0;
        let b = (rate + damping * omega_n * error0) / omega_d;
        let error = decay * (a * cos_wd + b * sin_wd);
        let error_rate = decay
            * (-damping * omega_n * (a * cos_wd + b * sin_wd)
                + (-a * omega_d * sin_wd + b * omega_d * cos_wd));
        (target + error, error_rate)
    } else if (damping - 1.0).abs() <= 1.0e-12 {
        let decay = (-omega_n * dt_s).exp();
        let a = error0;
        let b = rate + omega_n * error0;
        let error = decay * (a + b * dt_s);
        let error_rate = decay * (b - omega_n * (a + b * dt_s));
        (target + error, error_rate)
    } else {
        let root = (damping * damping - 1.0).sqrt();
        let r1 = -omega_n * (damping - root);
        let r2 = -omega_n * (damping + root);
        let c1 = (rate - r2 * error0) / (r1 - r2);
        let c2 = error0 - c1;
        let e1 = (r1 * dt_s).exp();
        let e2 = (r2 * dt_s).exp();
        let error = c1 * e1 + c2 * e2;
        let error_rate = c1 * r1 * e1 + c2 * r2 * e2;
        (target + error, error_rate)
    }
}

fn rate_limit_backlash_describing_function_with_resolution(
    input_amplitude: f64,
    frequency_hz: f64,
    max_rate_per_s: f64,
    backlash_half_width: f64,
    samples_per_cycle: usize,
    warmup_cycles: usize,
) -> Result<RateLimitBacklashDescribingFunction, EffectorError> {
    if !input_amplitude.is_finite() || input_amplitude <= 0.0 {
        return Err(EffectorError::InvalidLimits {
            reason: "describing-function input_amplitude must be finite and strictly positive",
        });
    }
    if !frequency_hz.is_finite() || frequency_hz <= 0.0 {
        return Err(EffectorError::InvalidLimits {
            reason: "describing-function frequency_hz must be finite and strictly positive",
        });
    }
    if !max_rate_per_s.is_finite() || max_rate_per_s <= 0.0 {
        return Err(EffectorError::InvalidLimits {
            reason: "describing-function max_rate_per_s must be finite and strictly positive",
        });
    }
    if !backlash_half_width.is_finite() || backlash_half_width < 0.0 {
        return Err(EffectorError::InvalidLimits {
            reason: "describing-function backlash_half_width must be finite and non-negative",
        });
    }
    if samples_per_cycle < 16 {
        return Err(EffectorError::InvalidLimits {
            reason: "describing-function samples_per_cycle must be at least 16",
        });
    }

    let samples = samples_per_cycle as f64;
    let dt_s = 1.0 / (frequency_hz * samples);
    let final_cycle_start = warmup_cycles * samples_per_cycle;
    let total_steps = final_cycle_start + samples_per_cycle;
    let mut rate_limited_position = 0.0;
    let mut backlash_output = 0.0;
    let mut sin_sum = 0.0;
    let mut cos_sum = 0.0;
    let mut rate_limited_steps = 0_usize;
    let mut backlash_hold_steps = 0_usize;

    for step in 0..total_steps {
        let theta = std::f64::consts::TAU * frequency_hz * (step as f64) * dt_s;
        let input = input_amplitude * theta.sin();
        let (limited, rate_limited) =
            rate_limited_track(rate_limited_position, input, max_rate_per_s, dt_s);
        rate_limited_position = limited;
        let (output, backlash_held) =
            backlash_play(rate_limited_position, backlash_output, backlash_half_width);
        backlash_output = output;

        if step >= final_cycle_start {
            sin_sum += backlash_output * theta.sin();
            cos_sum += backlash_output * theta.cos();
            if rate_limited {
                rate_limited_steps += 1;
            }
            if backlash_held {
                backlash_hold_steps += 1;
            }
        }
    }

    let sin_coeff = 2.0 * sin_sum / samples;
    let cos_coeff = 2.0 * cos_sum / samples;
    let output_amplitude = sin_coeff.hypot(cos_coeff);
    let phase_lead_rad = cos_coeff.atan2(sin_coeff);
    let phase_lag_rad = wrap_angle_rad(-phase_lead_rad);
    Ok(RateLimitBacklashDescribingFunction {
        input_amplitude,
        frequency_hz,
        output_amplitude,
        gain: output_amplitude / input_amplitude,
        phase_lag_rad,
        rate_limited_fraction: (rate_limited_steps as f64) / samples,
        backlash_hold_fraction: (backlash_hold_steps as f64) / samples,
    })
}

fn rate_limited_track(current: f64, target: f64, max_rate_per_s: f64, dt_s: f64) -> (f64, bool) {
    let requested_rate = (target - current) / dt_s;
    let clamped_rate = requested_rate.clamp(-max_rate_per_s, max_rate_per_s);
    (
        current + clamped_rate * dt_s,
        (requested_rate - clamped_rate).abs() > 1.0e-12 * requested_rate.abs().max(1.0),
    )
}

fn backlash_play(input: f64, output: f64, half_width: f64) -> (f64, bool) {
    if half_width == 0.0 {
        return (input, false);
    }
    let delta = input - output;
    if delta.abs() <= half_width {
        (output, true)
    } else {
        (input - half_width.copysign(delta), false)
    }
}

fn wrap_angle_rad(mut value: f64) -> f64 {
    while value > std::f64::consts::PI {
        value -= std::f64::consts::TAU;
    }
    while value < -std::f64::consts::PI {
        value += std::f64::consts::TAU;
    }
    value
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::float_cmp,
    clippy::panic,
    clippy::unwrap_used
)]
mod tests {
    use super::*;
    use openbmp_core::EffectorId;

    fn dt() -> Duration {
        Duration::from_seconds(0.001)
    }

    fn make_limits() -> EffectorLimits {
        EffectorLimits {
            min: -2.0,
            max: 2.0,
            max_rate_per_s: 10_000.0,
            deadband: 0.0,
            latency: Duration::from_seconds(0.0),
        }
    }

    fn make_params() -> SecondOrderServoParams {
        SecondOrderServoParams {
            natural_frequency_rad_s: 20.0,
            damping_ratio: 0.6,
            max_accel_per_s2: 1.0e8,
            backlash_half_width: 0.0,
        }
    }

    fn fresh_servo() -> SecondOrderServo {
        SecondOrderServo::new(
            EffectorId::from_path("test.second_order"),
            make_limits(),
            make_params(),
            dt(),
            0.0,
        )
        .expect("servo construction must succeed")
    }

    #[test]
    fn rejects_invalid_parameters() {
        let mut params = make_params();
        params.natural_frequency_rad_s = 0.0;
        assert!(matches!(
            SecondOrderServo::new(
                EffectorId::from_path("test.bad"),
                make_limits(),
                params,
                dt(),
                0.0,
            ),
            Err(EffectorError::InvalidLimits { .. })
        ));

        params = make_params();
        params.max_accel_per_s2 = f64::NAN;
        assert!(matches!(
            SecondOrderServo::new(
                EffectorId::from_path("test.bad"),
                make_limits(),
                params,
                dt(),
                0.0,
            ),
            Err(EffectorError::InvalidLimits { .. })
        ));
    }

    #[test]
    fn step_response_matches_closed_form_second_order() {
        let mut servo = fresh_servo();
        let target = 1.0;
        let steps = 1_000;
        for _ in 0..steps {
            servo.step(target, dt()).unwrap();
        }

        let t = f64::from(steps) * dt().as_seconds();
        let zeta = make_params().damping_ratio;
        let omega_n = make_params().natural_frequency_rad_s;
        let omega_d = omega_n * (1.0 - zeta * zeta).sqrt();
        let expected = target
            * (1.0
                - (-zeta * omega_n * t).exp()
                    * ((omega_d * t).cos()
                        + (zeta / (1.0 - zeta * zeta).sqrt()) * (omega_d * t).sin()));
        let error = (servo.current_state().actual - expected).abs();
        assert!(
            error <= 5.0e-3,
            "step response error {error} exceeds 0.5% band; actual {}, expected {expected}",
            servo.current_state().actual
        );
    }

    #[test]
    fn acceleration_limit_bounds_initial_motion() {
        let params = SecondOrderServoParams {
            max_accel_per_s2: 2.0,
            natural_frequency_rad_s: 1_000.0,
            damping_ratio: 1.0,
            backlash_half_width: 0.0,
        };
        let mut servo = SecondOrderServo::new(
            EffectorId::from_path("test.accel"),
            make_limits(),
            params,
            Duration::from_seconds(0.1),
            0.0,
        )
        .unwrap();
        let state = servo.step(1.0, Duration::from_seconds(0.1)).unwrap();
        assert!(state.rate_limited);
        assert!(
            (0.0..=0.02 + 1.0e-9).contains(&state.actual),
            "accel limit should keep first demand step under 0.02, got {}",
            state.actual
        );
    }

    #[test]
    fn backlash_holds_small_reversal_until_dead_zone_is_crossed() {
        let params = SecondOrderServoParams {
            natural_frequency_rad_s: 1_000.0,
            damping_ratio: 1.0,
            max_accel_per_s2: 1.0e8,
            backlash_half_width: 0.05,
        };
        let mut servo = SecondOrderServo::new(
            EffectorId::from_path("test.backlash"),
            make_limits(),
            params,
            Duration::from_seconds(0.01),
            0.0,
        )
        .unwrap();
        let small = servo.step(0.03, Duration::from_seconds(0.01)).unwrap();
        assert!(
            small.actual.abs() <= 1.0e-12,
            "small command inside backlash dead zone should hold, got {}",
            small.actual
        );
        let larger = servo.step(0.10, Duration::from_seconds(0.01)).unwrap();
        assert!(
            larger.actual > 0.0,
            "command outside backlash dead zone should engage, got {}",
            larger.actual
        );
    }

    #[test]
    fn latency_delays_command_before_servo_dynamics() {
        let limits = EffectorLimits {
            latency: Duration::from_seconds(0.002),
            ..make_limits()
        };
        let mut servo = SecondOrderServo::new(
            EffectorId::from_path("test.delay"),
            limits,
            make_params(),
            dt(),
            0.0,
        )
        .unwrap();
        assert!(servo.step(1.0, dt()).unwrap().actual.abs() <= 1.0e-12);
        assert!(servo.step(1.0, dt()).unwrap().actual.abs() <= 1.0e-12);
        assert!(servo.step(1.0, dt()).unwrap().actual > 0.0);
    }

    #[test]
    fn jam_fault_locks_position_and_clears_rate() {
        let mut servo = fresh_servo();
        servo.inject_fault(EffectorFault::Jam { at: 0.25 }).unwrap();
        let state = servo.step(-1.0, dt()).unwrap();
        assert!((state.actual - 0.25).abs() <= 1.0e-12);
        assert!(servo.actual_rate().abs() <= 1.0e-12);
    }

    #[test]
    fn oscillatory_fault_enters_before_bandwidth_dynamics() {
        let params = SecondOrderServoParams {
            natural_frequency_rad_s: 10_000.0,
            damping_ratio: 1.0,
            max_accel_per_s2: 1.0e8,
            backlash_half_width: 0.0,
        };
        let mut servo = SecondOrderServo::new(
            EffectorId::from_path("test.osc"),
            make_limits(),
            params,
            dt(),
            0.0,
        )
        .unwrap();
        servo
            .inject_fault(EffectorFault::Oscillatory {
                amplitude: 0.1,
                frequency_hz: 2.0,
                phase_rad: std::f64::consts::FRAC_PI_2,
            })
            .unwrap();
        let state = servo.step(0.0, dt()).unwrap();
        assert!((state.commanded - 0.1).abs() <= 1.0e-12);
        assert!(state.actual > 0.09);
        assert!(state.actual < 0.1);
        assert!(matches!(
            state.fault,
            Some(EffectorFault::Oscillatory { .. })
        ));
    }

    fn servo_sine_fundamental(
        input_amplitude: f64,
        frequency_hz: f64,
        max_rate_per_s: f64,
        backlash_half_width: f64,
    ) -> RateLimitBacklashDescribingFunction {
        let dt_s = 1.0 / (frequency_hz * DESCRIBING_FUNCTION_SAMPLES_PER_CYCLE as f64);
        let dt = Duration::from_seconds(dt_s);
        let limits = EffectorLimits {
            min: -2.0,
            max: 2.0,
            max_rate_per_s,
            deadband: 0.0,
            latency: Duration::from_seconds(0.0),
        };
        let params = SecondOrderServoParams {
            natural_frequency_rad_s: 2_500.0,
            damping_ratio: 1.0,
            max_accel_per_s2: 1.0e12,
            backlash_half_width,
        };
        let mut servo =
            SecondOrderServo::new(EffectorId::from_path("test.df"), limits, params, dt, 0.0)
                .unwrap();
        let final_cycle_start =
            DESCRIBING_FUNCTION_WARMUP_CYCLES * DESCRIBING_FUNCTION_SAMPLES_PER_CYCLE;
        let total_steps = final_cycle_start + DESCRIBING_FUNCTION_SAMPLES_PER_CYCLE;
        let samples = DESCRIBING_FUNCTION_SAMPLES_PER_CYCLE as f64;
        let mut sin_sum = 0.0;
        let mut cos_sum = 0.0;
        let mut rate_limited_steps = 0_usize;

        for step in 0..total_steps {
            let theta = std::f64::consts::TAU * frequency_hz * (step as f64) * dt_s;
            let command = input_amplitude * theta.sin();
            let state = servo.step(command, dt).unwrap();
            if step >= final_cycle_start {
                sin_sum += state.actual * theta.sin();
                cos_sum += state.actual * theta.cos();
                if state.rate_limited {
                    rate_limited_steps += 1;
                }
            }
        }

        let sin_coeff = 2.0 * sin_sum / samples;
        let cos_coeff = 2.0 * cos_sum / samples;
        let output_amplitude = sin_coeff.hypot(cos_coeff);
        RateLimitBacklashDescribingFunction {
            input_amplitude,
            frequency_hz,
            output_amplitude,
            gain: output_amplitude / input_amplitude,
            phase_lag_rad: wrap_angle_rad(-cos_coeff.atan2(sin_coeff)),
            rate_limited_fraction: rate_limited_steps as f64 / samples,
            backlash_hold_fraction: 0.0,
        }
    }

    #[test]
    fn rate_limit_backlash_fundamental_matches_describing_function() {
        let input_amplitude = 1.0;
        let frequency_hz = 2.0;
        let max_rate_per_s = 4.0;
        let backlash_half_width = 0.08;
        let expected = rate_limit_backlash_describing_function(
            input_amplitude,
            frequency_hz,
            max_rate_per_s,
            backlash_half_width,
        )
        .unwrap();
        assert!(expected.rate_limited_fraction > 0.9);
        assert!(expected.backlash_hold_fraction > 0.1);

        let measured = servo_sine_fundamental(
            input_amplitude,
            frequency_hz,
            max_rate_per_s,
            backlash_half_width,
        );
        let amplitude_error = (measured.output_amplitude - expected.output_amplitude).abs()
            / expected.output_amplitude;
        let phase_error = wrap_angle_rad(measured.phase_lag_rad - expected.phase_lag_rad).abs();
        assert!(
            amplitude_error <= 0.05,
            "measured amplitude {} differs from describing-function {} by {:.3}%",
            measured.output_amplitude,
            expected.output_amplitude,
            amplitude_error * 100.0
        );
        assert!(
            phase_error <= 0.05,
            "measured phase lag {} differs from describing-function {} by {phase_error}",
            measured.phase_lag_rad,
            expected.phase_lag_rad
        );
        assert!((measured.frequency_hz - expected.frequency_hz).abs() <= f64::EPSILON);
    }

    #[test]
    fn rate_limit_backlash_describing_function_rejects_invalid_inputs() {
        assert!(matches!(
            rate_limit_backlash_describing_function(0.0, 1.0, 1.0, 0.0),
            Err(EffectorError::InvalidLimits { .. })
        ));
        assert!(matches!(
            rate_limit_backlash_describing_function(1.0, 0.0, 1.0, 0.0),
            Err(EffectorError::InvalidLimits { .. })
        ));
        assert!(matches!(
            rate_limit_backlash_describing_function(1.0, 1.0, 0.0, 0.0),
            Err(EffectorError::InvalidLimits { .. })
        ));
        assert!(matches!(
            rate_limit_backlash_describing_function(1.0, 1.0, 1.0, -0.1),
            Err(EffectorError::InvalidLimits { .. })
        ));
    }
}
