[default.extend-words]
Drob = "Drob"
Fo = "Fo"
HAE = "HAE"
MSIS = "MSIS"
NED = "NED"
Ned = "Ned"
NEES = "NEES"
NIS = "NIS"
ND = "ND"
PN = "PN"
SITL = "SITL"
Shepard = "Shepard"
URE = "URE"
ned = "ned"
precess = "precess"
precesses = "precesses"
