[default.extend-words]
AAS = "AAS"
Commun = "Commun"
Drob = "Drob"
Comput = "Comput"
equil = "equil"
Fo = "Fo"
HAE = "HAE"
iz = "iz"
lod = "lod"
LOD = "LOD"
lod_s = "lod_s"
mis = "mis"
MSIS = "MSIS"
NED = "NED"
Ned = "Ned"
NEES = "NEES"
NIS = "NIS"
ND = "ND"
PN = "PN"
Plas = "Plas"
SITL = "SITL"
Shepard = "Shepard"
Stoer = "Stoer"
TIO = "TIO"
Trak = "Trak"
Tung = "Tung"
URE = "URE"
ned = "ned"
precess = "precess"
precessed = "precessed"
precessing = "precessing"
precesses = "precesses"
Rech = "Rech"
