//! External reference packages.
//!
//! OpenBMP is a flight-dynamics simulator, not a CFD, DSMC,
//! radiation-transport, or thermal-response code. Hypersonic studies
//! depend on offline reference data generated by those tools. This
//! module exposes a uniform package-loading surface with strict
//! provenance and envelope checks.
//!
//! Each package carries a *sidecar* metadata block declaring solver
//! version, governing equations, validity envelope, and content hash.
//! The [`ExternalReferencePackage::validate`] method enforces:
//!
//! 1. Envelope is well-formed (all bounds finite, lo ≤ hi).
//! 2. Required provenance fields are non-empty.
//! 3. Declared SHA-256 pins are syntactically valid.
//!
//! Consumers that read an external payload compute its SHA-256 digest
//! at their I/O boundary and pass the hex digest to
//! [`ExternalReferencePackage::validate_payload_hash_hex`]. Queries
//! against the package use
//! [`ExternalReferencePackage::query_within_envelope`], which **fails
//! closed** on out-of-envelope requests; the kernel never silently
//! extrapolates.

use crate::error::PhysicsError;

/// Reference-package kind classification.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum ReferencePackageKind {
    /// Continuum CFD aero coefficient deck (DPLR, LAURA, US3D, FUN3D,
    /// SU2, in-house academic CFD).
    ContinuumCfdAero,
    /// Radiation reference (NEQAIR or published radiative-heating
    /// tables).
    RadiationReference,
    /// Rarefied DSMC aero (SPARTA, DS2V/DS3V, published DSMC cases).
    RarefiedDsmcAero,
    /// Thermal-response reference (FIAT, TITAN, 3dFIAT, Icarus, CHAR,
    /// PATO, or published arc-jet cases).
    ThermalResponseReference,
    /// Trajectory reference (POST2, GMAT, Orekit, RocketPy, published
    /// mission reports).
    TrajectoryReference,
    /// Thermochemistry reference (NASA CEA, Cantera, Mutation++,
    /// published tables).
    ThermochemistryReference,
}

/// Validity envelope for a reference package.
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct EnvelopeBounds {
    /// Lower-bound query parameters (Mach, Reynolds, Knudsen, etc.).
    pub mach_lo: f64,
    /// Upper-bound Mach number.
    pub mach_hi: f64,
    /// Lower-bound altitude (m).
    pub altitude_lo_m: f64,
    /// Upper-bound altitude (m).
    pub altitude_hi_m: f64,
    /// Lower-bound angle of attack (rad).
    pub alpha_lo_rad: f64,
    /// Upper-bound angle of attack (rad).
    pub alpha_hi_rad: f64,
}

/// Provenance block carried by every reference package.
#[derive(Clone, Debug, PartialEq)]
pub struct ProvenanceBlock {
    /// Solver / tool name (e.g. "DPLR", "NEQAIR", "FIAT").
    pub solver_name: String,
    /// Solver version (free text).
    pub solver_version: String,
    /// License declaration (e.g. "public, NASA-released").
    pub license: String,
    /// Retrieval path (URL / DOI / report number).
    pub retrieval_path: String,
    /// Governing equations or model family.
    pub governing_equations: String,
    /// SHA-256 hash of the package payload (hex string, 64 chars).
    pub content_hash_sha256_hex: String,
}

impl ProvenanceBlock {
    /// Check that required fields are non-empty.
    pub(crate) fn validate(&self) -> Result<(), PhysicsError> {
        if self.solver_name.trim().is_empty()
            || self.solver_version.trim().is_empty()
            || self.license.trim().is_empty()
            || self.retrieval_path.trim().is_empty()
            || self.governing_equations.trim().is_empty()
        {
            return Err(PhysicsError::InvalidParameter {
                reason: "provenance block has empty required field",
            });
        }
        if !is_sha256_hex(&self.content_hash_sha256_hex) {
            return Err(PhysicsError::InvalidParameter {
                reason: "content_hash_sha256_hex must be 64 hex chars",
            });
        }
        Ok(())
    }
}

/// External reference package — wraps an envelope + provenance with a
/// uniform query interface.
#[derive(Clone, Debug, PartialEq)]
pub struct ExternalReferencePackage {
    /// Package kind.
    pub kind: ReferencePackageKind,
    /// Validity envelope.
    pub envelope: EnvelopeBounds,
    /// Provenance metadata.
    pub provenance: ProvenanceBlock,
}

/// Query coordinates against a reference package.
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct ReferenceQuery {
    /// Query Mach number.
    pub mach: f64,
    /// Query altitude (m).
    pub altitude_m: f64,
    /// Query angle of attack (rad).
    pub alpha_rad: f64,
}

impl ExternalReferencePackage {
    /// Validate envelope and provenance at load time.
    ///
    /// # Errors
    ///
    /// Returns [`PhysicsError::InvalidParameter`] when the envelope is
    /// malformed or provenance is incomplete.
    pub fn validate(&self) -> Result<(), PhysicsError> {
        self.provenance.validate()?;
        let e = &self.envelope;
        if !(e.mach_lo.is_finite()
            && e.mach_hi.is_finite()
            && e.mach_lo >= 0.0
            && e.mach_lo <= e.mach_hi)
        {
            return Err(PhysicsError::InvalidParameter {
                reason: "envelope mach bounds invalid or negative",
            });
        }
        if !(e.altitude_lo_m.is_finite()
            && e.altitude_hi_m.is_finite()
            && e.altitude_lo_m >= 0.0
            && e.altitude_lo_m <= e.altitude_hi_m)
        {
            return Err(PhysicsError::InvalidParameter {
                reason: "envelope altitude bounds invalid or negative",
            });
        }
        if !(e.alpha_lo_rad.is_finite()
            && e.alpha_hi_rad.is_finite()
            && e.alpha_lo_rad <= e.alpha_hi_rad)
        {
            return Err(PhysicsError::InvalidParameter {
                reason: "envelope alpha bounds invalid",
            });
        }
        Ok(())
    }

    /// Validate a consumer-supplied payload digest against the
    /// provenance pin.
    ///
    /// This method intentionally accepts a digest string rather than a
    /// file path or byte buffer. Payload reading and hashing belongs
    /// at the consuming deck/model boundary so `openbmp-physics`
    /// stays free of file I/O and extra hashing dependencies.
    ///
    /// # Errors
    ///
    /// Returns [`PhysicsError::InvalidParameter`] when the package
    /// metadata is malformed, the supplied digest is not a SHA-256
    /// hex string, or the digest does not match the provenance pin.
    pub fn validate_payload_hash_hex(&self, payload_sha256_hex: &str) -> Result<(), PhysicsError> {
        self.validate()?;
        if !is_sha256_hex(payload_sha256_hex) {
            return Err(PhysicsError::InvalidParameter {
                reason: "payload sha256 must be 64 hex chars",
            });
        }
        if !self
            .provenance
            .content_hash_sha256_hex
            .eq_ignore_ascii_case(payload_sha256_hex)
        {
            return Err(PhysicsError::InvalidParameter {
                reason: "external reference package payload hash mismatch",
            });
        }
        Ok(())
    }

    /// Check whether a query lies within the declared envelope.
    #[must_use]
    pub fn query_in_envelope(&self, q: ReferenceQuery) -> bool {
        let e = &self.envelope;
        (e.mach_lo..=e.mach_hi).contains(&q.mach)
            && (e.altitude_lo_m..=e.altitude_hi_m).contains(&q.altitude_m)
            && (e.alpha_lo_rad..=e.alpha_hi_rad).contains(&q.alpha_rad)
    }

    /// Normalised distance of `q` to the nearest envelope face.
    /// Negative when `q` is inside (units of envelope half-span).
    #[must_use]
    pub fn envelope_margin(&self, q: ReferenceQuery) -> f64 {
        let e = &self.envelope;
        let mach_mid = 0.5 * (e.mach_lo + e.mach_hi);
        let mach_half = 0.5 * (e.mach_hi - e.mach_lo).max(1.0e-9);
        let alt_mid = 0.5 * (e.altitude_lo_m + e.altitude_hi_m);
        let alt_half = 0.5 * (e.altitude_hi_m - e.altitude_lo_m).max(1.0e-9);
        let alpha_mid = 0.5 * (e.alpha_lo_rad + e.alpha_hi_rad);
        let alpha_half = 0.5 * (e.alpha_hi_rad - e.alpha_lo_rad).max(1.0e-9);
        let dm = (q.mach - mach_mid).abs() / mach_half - 1.0;
        let dh = (q.altitude_m - alt_mid).abs() / alt_half - 1.0;
        let da = (q.alpha_rad - alpha_mid).abs() / alpha_half - 1.0;
        dm.max(dh).max(da)
    }

    /// Fail-closed wrapper used by consumers.
    ///
    /// # Errors
    ///
    /// Returns [`PhysicsError::OutOfEnvelope`] when the query falls
    /// outside the declared envelope and no extrapolation policy has
    /// been opted into.
    pub fn query_within_envelope(&self, q: ReferenceQuery) -> Result<(), PhysicsError> {
        if !self.query_in_envelope(q) {
            return Err(PhysicsError::OutOfEnvelope {
                reason: "external reference package: query outside declared envelope",
            });
        }
        Ok(())
    }

    /// Validate package metadata, payload hash, and query envelope in
    /// one fail-closed check.
    ///
    /// # Errors
    ///
    /// Returns the same errors as [`Self::validate`],
    /// [`Self::validate_payload_hash_hex`], or
    /// [`Self::query_within_envelope`].
    pub fn validate_query_and_payload_hash(
        &self,
        q: ReferenceQuery,
        payload_sha256_hex: &str,
    ) -> Result<(), PhysicsError> {
        self.validate_payload_hash_hex(payload_sha256_hex)?;
        self.query_within_envelope(q)
    }
}

fn is_sha256_hex(s: &str) -> bool {
    s.len() == 64 && s.chars().all(|c| c.is_ascii_hexdigit())
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::float_cmp,
    clippy::missing_panics_doc,
    clippy::similar_names
)]
mod tests {
    use super::*;

    fn ok_provenance() -> ProvenanceBlock {
        ProvenanceBlock {
            solver_name: "test-cfd".into(),
            solver_version: "1.0.0".into(),
            license: "public".into(),
            retrieval_path: "https://example.org/deck.toml".into(),
            governing_equations: "Navier-Stokes".into(),
            content_hash_sha256_hex: "a".repeat(64),
        }
    }

    fn ok_envelope() -> EnvelopeBounds {
        EnvelopeBounds {
            mach_lo: 5.0,
            mach_hi: 25.0,
            altitude_lo_m: 30_000.0,
            altitude_hi_m: 100_000.0,
            alpha_lo_rad: -0.3,
            alpha_hi_rad: 0.3,
        }
    }

    #[test]
    fn well_formed_package_validates() {
        let p = ExternalReferencePackage {
            kind: ReferencePackageKind::ContinuumCfdAero,
            envelope: ok_envelope(),
            provenance: ok_provenance(),
        };
        p.validate().unwrap();
    }

    #[test]
    fn empty_solver_name_rejected() {
        let mut p = ok_provenance();
        p.solver_name = String::new();
        let pkg = ExternalReferencePackage {
            kind: ReferencePackageKind::ContinuumCfdAero,
            envelope: ok_envelope(),
            provenance: p,
        };
        assert!(matches!(
            pkg.validate(),
            Err(PhysicsError::InvalidParameter { .. })
        ));
    }

    #[test]
    fn whitespace_only_provenance_field_rejected() {
        let mut p = ok_provenance();
        p.retrieval_path = "   ".into();
        let pkg = ExternalReferencePackage {
            kind: ReferencePackageKind::ContinuumCfdAero,
            envelope: ok_envelope(),
            provenance: p,
        };
        assert!(matches!(
            pkg.validate(),
            Err(PhysicsError::InvalidParameter { .. })
        ));
    }

    #[test]
    fn bad_hash_rejected() {
        let mut p = ok_provenance();
        p.content_hash_sha256_hex = "deadbeef".into();
        let pkg = ExternalReferencePackage {
            kind: ReferencePackageKind::RadiationReference,
            envelope: ok_envelope(),
            provenance: p,
        };
        assert!(matches!(
            pkg.validate(),
            Err(PhysicsError::InvalidParameter { .. })
        ));
    }

    #[test]
    fn negative_physical_envelope_bounds_rejected() {
        let mut envelope = ok_envelope();
        envelope.mach_lo = -1.0;
        let pkg = ExternalReferencePackage {
            kind: ReferencePackageKind::ContinuumCfdAero,
            envelope,
            provenance: ok_provenance(),
        };
        assert!(matches!(
            pkg.validate(),
            Err(PhysicsError::InvalidParameter { .. })
        ));

        let mut envelope = ok_envelope();
        envelope.altitude_lo_m = -1.0;
        let pkg = ExternalReferencePackage {
            kind: ReferencePackageKind::ContinuumCfdAero,
            envelope,
            provenance: ok_provenance(),
        };
        assert!(matches!(
            pkg.validate(),
            Err(PhysicsError::InvalidParameter { .. })
        ));
    }

    #[test]
    fn payload_hash_match_passes_case_insensitively() {
        let pkg = ExternalReferencePackage {
            kind: ReferencePackageKind::RadiationReference,
            envelope: ok_envelope(),
            provenance: ok_provenance(),
        };
        pkg.validate_payload_hash_hex(&"A".repeat(64)).unwrap();
    }

    #[test]
    fn payload_hash_mismatch_rejected() {
        let pkg = ExternalReferencePackage {
            kind: ReferencePackageKind::RadiationReference,
            envelope: ok_envelope(),
            provenance: ok_provenance(),
        };
        assert!(matches!(
            pkg.validate_payload_hash_hex(&"b".repeat(64)),
            Err(PhysicsError::InvalidParameter { .. })
        ));
    }

    #[test]
    fn payload_hash_malformed_rejected() {
        let pkg = ExternalReferencePackage {
            kind: ReferencePackageKind::RadiationReference,
            envelope: ok_envelope(),
            provenance: ok_provenance(),
        };
        assert!(matches!(
            pkg.validate_payload_hash_hex("not-a-sha"),
            Err(PhysicsError::InvalidParameter { .. })
        ));
    }

    #[test]
    fn inverted_envelope_rejected() {
        let mut e = ok_envelope();
        e.mach_lo = 30.0;
        e.mach_hi = 5.0;
        let pkg = ExternalReferencePackage {
            kind: ReferencePackageKind::ContinuumCfdAero,
            envelope: e,
            provenance: ok_provenance(),
        };
        assert!(matches!(
            pkg.validate(),
            Err(PhysicsError::InvalidParameter { .. })
        ));
    }

    #[test]
    fn query_inside_envelope_passes() {
        let pkg = ExternalReferencePackage {
            kind: ReferencePackageKind::ContinuumCfdAero,
            envelope: ok_envelope(),
            provenance: ok_provenance(),
        };
        let q = ReferenceQuery {
            mach: 10.0,
            altitude_m: 60_000.0,
            alpha_rad: 0.1,
        };
        pkg.query_within_envelope(q).unwrap();
        assert!(pkg.query_in_envelope(q));
        assert!(pkg.envelope_margin(q) < 0.0);
    }

    #[test]
    fn query_outside_envelope_fails_closed() {
        let pkg = ExternalReferencePackage {
            kind: ReferencePackageKind::ContinuumCfdAero,
            envelope: ok_envelope(),
            provenance: ok_provenance(),
        };
        let q_too_fast = ReferenceQuery {
            mach: 100.0,
            altitude_m: 60_000.0,
            alpha_rad: 0.0,
        };
        assert!(!pkg.query_in_envelope(q_too_fast));
        assert!(matches!(
            pkg.query_within_envelope(q_too_fast),
            Err(PhysicsError::OutOfEnvelope { .. })
        ));
        assert!(pkg.envelope_margin(q_too_fast) > 0.0);
    }

    #[test]
    fn query_and_payload_hash_validation_combines_checks() {
        let pkg = ExternalReferencePackage {
            kind: ReferencePackageKind::ContinuumCfdAero,
            envelope: ok_envelope(),
            provenance: ok_provenance(),
        };
        let q = ReferenceQuery {
            mach: 10.0,
            altitude_m: 60_000.0,
            alpha_rad: 0.1,
        };
        pkg.validate_query_and_payload_hash(q, &"a".repeat(64))
            .unwrap();

        let q_too_high = ReferenceQuery {
            altitude_m: 200_000.0,
            ..q
        };
        assert!(matches!(
            pkg.validate_query_and_payload_hash(q_too_high, &"a".repeat(64)),
            Err(PhysicsError::OutOfEnvelope { .. })
        ));
    }
}
