//! Offline T0 trajectory-correction drivers.
//!
//! The first driver wires [`DifferentialCorrector`] to a deterministic
//! two-body RK4 propagation loop. It targets an orbital apogee radius by
//! varying the tangential cutoff speed, then packages the converged reference
//! profile as a versioned postcard I-load.

use alloc::string::String;
use alloc::vec::Vec;

use openbmp_core::SimTime;
use openbmp_physics::WGS84_MU_M3_S2;
use openbmp_physics::profile::{
    BallisticState, ForwardSimulationProvenance, ForwardSimulationSource, TerminalCondition,
};

use crate::corrector::{DifferentialCorrection, DifferentialCorrector};
use crate::iload::{
    ILoadHeader, ILoadPayload, ReferenceProfileSample, SynthesisMetadata, TrajoptError,
    encode_iload_payload,
};

const MAX_REFERENCE_SAMPLES: usize = 100_001;

/// Configuration for the T0 two-body apogee targeting driver.
#[derive(Clone, Debug, PartialEq)]
pub struct TwoBodyApogeeTargeting {
    /// Initial inertial radius on the x-axis, in m.
    pub initial_radius_m: f64,
    /// Initial tangential speed guess on the y-axis, in m/s.
    pub initial_tangential_speed_m_s: f64,
    /// Target apogee radius from the central body, in m.
    pub target_apogee_radius_m: f64,
    /// Coast duration from the cutoff state before residual evaluation, in s.
    pub coast_duration_s: f64,
    /// Fixed RK4 propagation step, in s.
    pub step_s: f64,
    /// Central-body gravitational parameter, in m^3/s^2.
    pub mu_m3_s2: f64,
    /// Differential corrector settings.
    pub corrector: DifferentialCorrector,
    /// Deterministic synthesis seed recorded in the I-load header.
    pub synthesis_seed: u64,
    /// Opaque scenario/driver digest recorded in the I-load metadata.
    pub scenario_digest: String,
    /// Source revision recorded in the I-load metadata.
    pub source_revision: String,
    /// Producer name recorded in the I-load header.
    pub producer: String,
}

impl TwoBodyApogeeTargeting {
    /// Construct a WGS84-mu driver with conservative T0 defaults.
    #[must_use]
    pub fn wgs84(
        initial_radius_m: f64,
        target_apogee_radius_m: f64,
        initial_tangential_speed_m_s: f64,
    ) -> Self {
        Self {
            initial_radius_m,
            initial_tangential_speed_m_s,
            target_apogee_radius_m,
            coast_duration_s: 0.0,
            step_s: 10.0,
            mu_m3_s2: WGS84_MU_M3_S2,
            corrector: DifferentialCorrector {
                residual_tolerance: 1.0e-2,
                max_iterations: 100,
                ..DifferentialCorrector::default()
            },
            synthesis_seed: 0,
            scenario_digest: "two-body-apogee".to_owned(),
            source_revision: "working-tree".to_owned(),
            producer: "openbmp-trajopt".to_owned(),
        }
    }
}

/// Result of a T0 two-body apogee correction run.
#[derive(Clone, Debug, PartialEq)]
pub struct TwoBodyApogeeReport {
    /// Differential-correction result. Inspect `converged` before consuming
    /// the I-load fields.
    pub correction: DifferentialCorrection,
    /// Terminal state at the final corrected iterate.
    pub terminal_state: BallisticState,
    /// Reference profile generated by the final corrected propagation.
    pub reference_profile: Vec<ReferenceProfileSample>,
    /// I-load payload when the correction converged.
    pub iload_payload: Option<ILoadPayload>,
    /// Postcard-serialized I-load payload when the correction converged.
    pub encoded_iload: Option<Vec<u8>>,
}

/// Run the T0 two-body apogee targeting driver.
///
/// The driver varies one forward-only free variable, tangential cutoff speed,
/// and targets a closed [`TerminalCondition::ApogeeRadius`]. Non-convergence is
/// reported honestly in [`TwoBodyApogeeReport::correction`] rather than mapped
/// to an error.
///
/// # Errors
///
/// Returns [`TrajoptError`] when the configuration is malformed, propagation
/// leaves the finite bound-conic envelope, or I-load serialization fails.
pub fn correct_two_body_apogee(
    config: &TwoBodyApogeeTargeting,
) -> Result<TwoBodyApogeeReport, TrajoptError> {
    validate_config(config)?;
    let condition = TerminalCondition::ApogeeRadius {
        radius_m: config.target_apogee_radius_m,
    };
    let correction = config.corrector.solve(
        &condition,
        config.mu_m3_s2,
        &[config.initial_tangential_speed_m_s],
        |free| {
            let speed = first_free_variable(free)?;
            let (state, _) = propagate_two_body(
                config.initial_radius_m,
                speed,
                config.coast_duration_s,
                config.step_s,
                config.mu_m3_s2,
            )?;
            Ok(state)
        },
    )?;
    let corrected_speed_m_s = first_free_variable(&correction.free_variables)?;
    let (terminal_state, reference_profile) = propagate_two_body(
        config.initial_radius_m,
        corrected_speed_m_s,
        config.coast_duration_s,
        config.step_s,
        config.mu_m3_s2,
    )?;
    let (iload_payload, encoded_iload) = if correction.converged {
        let payload = ILoadPayload {
            header: ILoadHeader::new(&condition, config.synthesis_seed, config.producer.clone()),
            metadata: SynthesisMetadata {
                scenario_digest: config.scenario_digest.clone(),
                source_revision: config.source_revision.clone(),
                method: "two_body_apogee_single_shooting".to_owned(),
            },
            event_bindings_postcard: Vec::new(),
            gain_tables: Vec::new(),
            reference_profile: reference_profile.clone(),
        };
        let encoded = encode_iload_payload(&payload)?;
        (Some(payload), Some(encoded))
    } else {
        (None, None)
    };
    Ok(TwoBodyApogeeReport {
        correction,
        terminal_state,
        reference_profile,
        iload_payload,
        encoded_iload,
    })
}

fn validate_config(config: &TwoBodyApogeeTargeting) -> Result<(), TrajoptError> {
    if !config.initial_radius_m.is_finite() || config.initial_radius_m <= 0.0 {
        return Err(TrajoptError::InvalidPayload {
            reason: "initial radius must be finite and positive",
        });
    }
    if !config.initial_tangential_speed_m_s.is_finite()
        || config.initial_tangential_speed_m_s <= 0.0
    {
        return Err(TrajoptError::InvalidPayload {
            reason: "initial tangential speed must be finite and positive",
        });
    }
    if !config.target_apogee_radius_m.is_finite() || config.target_apogee_radius_m <= 0.0 {
        return Err(TrajoptError::InvalidPayload {
            reason: "target apogee radius must be finite and positive",
        });
    }
    if !config.coast_duration_s.is_finite() || config.coast_duration_s < 0.0 {
        return Err(TrajoptError::InvalidPayload {
            reason: "coast duration must be finite and non-negative",
        });
    }
    if !config.step_s.is_finite() || config.step_s <= 0.0 {
        return Err(TrajoptError::InvalidPayload {
            reason: "propagation step must be finite and positive",
        });
    }
    if !config.mu_m3_s2.is_finite() || config.mu_m3_s2 <= 0.0 {
        return Err(TrajoptError::InvalidPayload {
            reason: "gravity parameter must be finite and positive",
        });
    }
    let samples = reference_sample_count(config.coast_duration_s, config.step_s)?;
    if samples > MAX_REFERENCE_SAMPLES {
        return Err(TrajoptError::InvalidPayload {
            reason: "reference profile would exceed the T0 sample limit",
        });
    }
    Ok(())
}

fn first_free_variable(free: &[f64]) -> Result<f64, TrajoptError> {
    let Some(&speed) = free.first() else {
        return Err(TrajoptError::InvalidPayload {
            reason: "two-body apogee driver requires one free speed variable",
        });
    };
    if !speed.is_finite() || speed <= 0.0 {
        return Err(TrajoptError::InvalidPayload {
            reason: "two-body apogee speed variable must be finite and positive",
        });
    }
    Ok(speed)
}

#[derive(Clone, Copy, Debug, PartialEq)]
struct TwoBodyState {
    position_eci_m: [f64; 3],
    velocity_eci_m_s: [f64; 3],
    time_s: f64,
}

fn propagate_two_body(
    initial_radius_m: f64,
    initial_tangential_speed_m_s: f64,
    coast_duration_s: f64,
    step_s: f64,
    mu_m3_s2: f64,
) -> Result<(BallisticState, Vec<ReferenceProfileSample>), TrajoptError> {
    let mut state = TwoBodyState {
        position_eci_m: [initial_radius_m, 0.0, 0.0],
        velocity_eci_m_s: [0.0, initial_tangential_speed_m_s, 0.0],
        time_s: 0.0,
    };
    let mut profile = Vec::with_capacity(reference_sample_count(coast_duration_s, step_s)?);
    profile.push(reference_sample(state)?);
    while state.time_s < coast_duration_s {
        let remaining_s = coast_duration_s - state.time_s;
        let dt_s = remaining_s.min(step_s);
        state = rk4_two_body_step(state, dt_s, mu_m3_s2)?;
        profile.push(reference_sample(state)?);
    }
    let sim_time = SimTime::from_seconds(state.time_s);
    let provenance = ForwardSimulationProvenance::for_state(
        state.position_eci_m,
        state.velocity_eci_m_s,
        0.0,
        sim_time,
        ForwardSimulationSource::RunnerTelemetryState,
    );
    let ballistic = BallisticState::from_forward_simulation(
        state.position_eci_m,
        state.velocity_eci_m_s,
        0.0,
        sim_time,
        provenance,
    )
    .map_err(|_| TrajoptError::InvalidPayload {
        reason: "two-body propagation produced an invalid terminal state",
    })?;
    Ok((ballistic, profile))
}

fn reference_sample(state: TwoBodyState) -> Result<ReferenceProfileSample, TrajoptError> {
    let radius_m = norm3(state.position_eci_m);
    let speed_m_s = norm3(state.velocity_eci_m_s);
    if radius_m <= f64::EPSILON || speed_m_s <= f64::EPSILON {
        return Err(TrajoptError::InvalidPayload {
            reason: "two-body reference sample is degenerate",
        });
    }
    let radial_speed_m_s = dot3(state.position_eci_m, state.velocity_eci_m_s) / radius_m;
    Ok(ReferenceProfileSample {
        time_s: state.time_s,
        radius_m,
        speed_m_s,
        flight_path_angle_rad: (radial_speed_m_s / speed_m_s).clamp(-1.0, 1.0).asin(),
    })
}

fn reference_sample_count(coast_duration_s: f64, step_s: f64) -> Result<usize, TrajoptError> {
    if !coast_duration_s.is_finite() || !step_s.is_finite() || step_s <= 0.0 {
        return Err(TrajoptError::InvalidPayload {
            reason: "reference sample count requires finite duration and positive step",
        });
    }
    let steps = (coast_duration_s / step_s).ceil();
    if !steps.is_finite() || steps < 0.0 || steps > (usize::MAX - 1) as f64 {
        return Err(TrajoptError::InvalidPayload {
            reason: "reference sample count is outside supported range",
        });
    }
    Ok(steps as usize + 1)
}

fn rk4_two_body_step(
    state: TwoBodyState,
    dt_s: f64,
    mu_m3_s2: f64,
) -> Result<TwoBodyState, TrajoptError> {
    let (k1_r, k1_v) = two_body_derivative(state, mu_m3_s2)?;
    let s2 = offset_state(state, k1_r, k1_v, 0.5 * dt_s)?;
    let (k2_r, k2_v) = two_body_derivative(s2, mu_m3_s2)?;
    let s3 = offset_state(state, k2_r, k2_v, 0.5 * dt_s)?;
    let (k3_r, k3_v) = two_body_derivative(s3, mu_m3_s2)?;
    let s4 = offset_state(state, k3_r, k3_v, dt_s)?;
    let (k4_r, k4_v) = two_body_derivative(s4, mu_m3_s2)?;
    let one_sixth_dt = dt_s / 6.0;
    let position_eci_m = [
        state.position_eci_m[0]
            + (k1_r[0] + 2.0 * k2_r[0] + 2.0 * k3_r[0] + k4_r[0]) * one_sixth_dt,
        state.position_eci_m[1]
            + (k1_r[1] + 2.0 * k2_r[1] + 2.0 * k3_r[1] + k4_r[1]) * one_sixth_dt,
        state.position_eci_m[2]
            + (k1_r[2] + 2.0 * k2_r[2] + 2.0 * k3_r[2] + k4_r[2]) * one_sixth_dt,
    ];
    let velocity_eci_m_s = [
        state.velocity_eci_m_s[0]
            + (k1_v[0] + 2.0 * k2_v[0] + 2.0 * k3_v[0] + k4_v[0]) * one_sixth_dt,
        state.velocity_eci_m_s[1]
            + (k1_v[1] + 2.0 * k2_v[1] + 2.0 * k3_v[1] + k4_v[1]) * one_sixth_dt,
        state.velocity_eci_m_s[2]
            + (k1_v[2] + 2.0 * k2_v[2] + 2.0 * k3_v[2] + k4_v[2]) * one_sixth_dt,
    ];
    let next = TwoBodyState {
        position_eci_m,
        velocity_eci_m_s,
        time_s: state.time_s + dt_s,
    };
    validate_state(next)?;
    Ok(next)
}

fn offset_state(
    state: TwoBodyState,
    dr_dt: [f64; 3],
    dv_dt: [f64; 3],
    dt_s: f64,
) -> Result<TwoBodyState, TrajoptError> {
    let offset = TwoBodyState {
        position_eci_m: [
            state.position_eci_m[0] + dr_dt[0] * dt_s,
            state.position_eci_m[1] + dr_dt[1] * dt_s,
            state.position_eci_m[2] + dr_dt[2] * dt_s,
        ],
        velocity_eci_m_s: [
            state.velocity_eci_m_s[0] + dv_dt[0] * dt_s,
            state.velocity_eci_m_s[1] + dv_dt[1] * dt_s,
            state.velocity_eci_m_s[2] + dv_dt[2] * dt_s,
        ],
        time_s: state.time_s + dt_s,
    };
    validate_state(offset)?;
    Ok(offset)
}

fn two_body_derivative(
    state: TwoBodyState,
    mu_m3_s2: f64,
) -> Result<([f64; 3], [f64; 3]), TrajoptError> {
    validate_state(state)?;
    let radius_m = norm3(state.position_eci_m);
    if radius_m <= f64::EPSILON {
        return Err(TrajoptError::InvalidPayload {
            reason: "two-body state radius is degenerate",
        });
    }
    let inv_r3 = 1.0 / (radius_m * radius_m * radius_m);
    let accel = [
        -mu_m3_s2 * state.position_eci_m[0] * inv_r3,
        -mu_m3_s2 * state.position_eci_m[1] * inv_r3,
        -mu_m3_s2 * state.position_eci_m[2] * inv_r3,
    ];
    Ok((state.velocity_eci_m_s, accel))
}

fn validate_state(state: TwoBodyState) -> Result<(), TrajoptError> {
    if !state.time_s.is_finite()
        || !state.position_eci_m.iter().all(|value| value.is_finite())
        || !state.velocity_eci_m_s.iter().all(|value| value.is_finite())
    {
        return Err(TrajoptError::InvalidPayload {
            reason: "two-body propagation produced non-finite state",
        });
    }
    Ok(())
}

fn dot3(a: [f64; 3], b: [f64; 3]) -> f64 {
    a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
}

fn norm3(value: [f64; 3]) -> f64 {
    dot3(value, value).sqrt()
}

#[cfg(test)]
#[allow(clippy::expect_used, clippy::unwrap_used)]
mod tests {
    use super::*;

    #[test]
    fn two_body_apogee_driver_emits_converged_iload() {
        let perigee_m = 6_778_000.0_f64;
        let target_apogee_m = 7_578_000.0_f64;
        let circular_speed = (WGS84_MU_M3_S2 / perigee_m).sqrt();
        let mut config = TwoBodyApogeeTargeting::wgs84(perigee_m, target_apogee_m, circular_speed);
        config.coast_duration_s = 120.0;
        config.step_s = 20.0;
        config.source_revision = "unit-test".to_owned();

        let report = correct_two_body_apogee(&config).expect("driver should run");

        assert!(report.correction.converged, "{report:?}");
        assert!(report.correction.residual.norm < 1.0e-2, "{report:?}");
        assert!(report.correction.free_variables[0] > circular_speed);
        assert!(report.iload_payload.is_some());
        assert!(
            report
                .encoded_iload
                .as_ref()
                .is_some_and(|bytes| !bytes.is_empty())
        );
        assert!(report.reference_profile.len() > 1);
        let decoded: ILoadPayload =
            postcard::from_bytes(report.encoded_iload.as_ref().unwrap()).unwrap();
        assert_eq!(Some(decoded), report.iload_payload);
    }

    #[test]
    fn two_body_apogee_driver_reports_non_convergence_without_iload() {
        let perigee_m = 6_778_000.0_f64;
        let target_apogee_m = 7_578_000.0_f64;
        let circular_speed = (WGS84_MU_M3_S2 / perigee_m).sqrt();
        let mut config = TwoBodyApogeeTargeting::wgs84(perigee_m, target_apogee_m, circular_speed);
        config.corrector.max_iterations = 0;

        let report = correct_two_body_apogee(&config).expect("driver should run");

        assert!(!report.correction.converged, "{report:?}");
        assert_eq!(report.correction.iterations, 0);
        assert!(report.iload_payload.is_none());
        assert!(report.encoded_iload.is_none());
    }
}
